services:
  postgres:
    image: postgres:16
    container_name: simple-app-db
    restart: always
    environment:
      POSTGRES_DB: simple-app
      POSTGRES_USER: janek
      POSTGRES_PASSWORD: Janek@1234
    ports:
      - "5433:5432"
# 학습용이라 굳이 volume은 사용하지 않음
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:
