/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.jetbrains.exposed.v1.core.JoinType
import org.jetbrains.exposed.v1.core.StdOutSqlLogger
import org.jetbrains.exposed.v1.core.count
import org.jetbrains.exposed.v1.core.eq
import org.jetbrains.exposed.v1.jdbc.Database
import org.jetbrains.exposed.v1.jdbc.SchemaUtils
import org.jetbrains.exposed.v1.jdbc.insert
import org.jetbrains.exposed.v1.jdbc.select
import org.jetbrains.exposed.v1.jdbc.selectAll
import org.jetbrains.exposed.v1.jdbc.transactions.transaction

fun main() {
    Database.connect("jdbc:h2:mem:test", driver = "org.h2.Driver")

    transaction {
        addLogger(StdOutSqlLogger)
        SchemaUtils.create(Tasks)

        val user = User.insert {
            it[name] = "User 1"
        }.get(User.id)

        val taskId = Tasks.insert {
            it[Tasks.user] = user
            it[title] = "Task 1"
            it[description] = "Description 1"
        } get Tasks.id

        val secondTaskId = Tasks.insert {
            it[Tasks.user] = user
            it[title] = "Task 2"
            it[description] = "Description 2"
            it[isCompleted] = true
        } get Tasks.id

        println("Created new tasks with ids: $taskId, $secondTaskId")

        Tasks.select(Tasks.id.count(), Tasks.isCompleted)
            .groupBy(Tasks.isCompleted)
            .forEach { println("${it[Tasks.isCompleted]}: ${it[Tasks.id.count()]}") }

        println("Remaining tasks: ${Tasks.selectAll().toList()}")

        User.join(Tasks, JoinType.INNER, additionalConstraint = { Tasks.user eq User.id })
            .select(User.name, Tasks.title)
            .forEach { println("${it[User.name]}: ${it[Tasks.title]}") }
    }
}
